# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  product_repository:
      class: AppBundle\Domain\Model\ProductRepository
      factory_service: doctrine.orm.entity_manager
      factory_method: getRepository
      arguments:
        - AppBundle\Domain\Model\Product
  merchant_repository:
      class: AppBundle\Domain\Model\MerchantRepository
      factory_service: doctrine.orm.entity_manager
      factory_method: getRepository
      arguments:
        - AppBundle\Domain\Model\Merchant
  migrate_product_from_file:
      class: AppBundle\Application\Handler\Command\MigrateProductFromFileCommand
      arguments:
          - @product_repository
          - @merchant_repository
