<?php

namespace Import\Bundle\Entity\Default;

/**
 * MerchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantRepository extends \Doctrine\ORM\EntityRepository
{
}
