# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.manager.item:
        class: AppBundle\Entity\ItemManager
        arguments:
            em: "@doctrine.orm.entity_manager"

    app.manager.import:
        class: AppBundle\Entity\ImportManager
        arguments:
            em: "@doctrine.orm.entity_manager"