-- MySQL Script generated by MySQL Workbench
-- 04/16/16 13:19:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_company_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `new_company_db` ;

-- -----------------------------------------------------
-- Schema new_company_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_company_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `new_company_db` ;

-- -----------------------------------------------------
-- Table `new_company_db`.`merchants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `new_company_db`.`merchants` ;

CREATE TABLE IF NOT EXISTS `new_company_db`.`merchants` (
  `merchant_id` INT(10) NOT NULL AUTO_INCREMENT,
  `merchant_name` VARCHAR(100) NOT NULL,
  `merchant_address` VARCHAR(200) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`merchant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `new_company_db`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `new_company_db`.`items` ;

CREATE TABLE IF NOT EXISTS `new_company_db`.`items` (
  `item_id` INT(10) NOT NULL AUTO_INCREMENT,
  `merchant_id` INT(4) NOT NULL,
  `item_title` VARCHAR(100) NOT NULL,
  `item_description` VARCHAR(500) NOT NULL,
  `item_price` FLOAT(5,2) NOT NULL,
  `item_init_date` TIMESTAMP NULL DEFAULT NULL,
  `item_exp_date` TIMESTAMP NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_merchants_idx` (`merchant_id` ASC),
  CONSTRAINT `fk_items_merchants`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `new_company_db`.`merchants` (`merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
