<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all products by Merchant name
     * @return array
     */
    public function findGroupByMerchantName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.merchantName, COUNT(p) cont FROM AppBundle:Product p GROUP BY p.merchantName'
            )
            ->getResult();
    }

    /**
     * Find all products of the same month
     * @return array
     */
    public function findGroupByMonth()
    {
        $rsm = new ResultSetMapping;
        $rsm->addEntityResult('AppBundle:Product', 'p');
        $rsm->addScalarResult('month', 'month');
        $rsm->addScalarResult('total', 'total');
        //I use a createNativeQuery function because MONTH function is not allowed without external libraries
        return $this->getEntityManager()
            ->createNativeQuery(
                'SELECT MONTHNAME(init_date) AS month, COUNT(id) AS total FROM product GROUP BY MONTHNAME(init_date);', $rsm
            )->getResult();
    }
}
